version: '2'
volumes:
  gems:
    external:
        name: gems-${EXECUTOR_NUMBER}-ruby-2.3
services:
  app:
    build:
      context: .
      args:
        host_uid: $HOST_UID
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    environment:
    - GEM_HOME=/gems
    - BUNDLE_PATH=/gems
    volumes:
    - .:/code
    - gems:/gems
